### ISSUE TITLE
Historical and audit of the changes done in the MONARC

### ISSUE THREAD

**Issue by adulau** [monarc-project/MonarcAppFO#73] opened 2018-03-08 14:03 UTC
Historical and audit of the changes done in the MONARC. It would be useful to have the ability to trace back the history of changes done by a risk analyst. A log entry with an history would be nice per change.

**Comment by jfrocha** [comment] 2019-07-29 13:30
Duplicate of #17

**Closed by jfrocha** 2019-07-29 13:30 UTC
Labels: enhancement
