### ISSUE TITLE
SoA error on existing risk assessment

### ISSUE THREAD

**Issue by eromang** [monarc-project/MonarcAppFO#149] opened 2019-03-25 15:21 UTC
Dear all,

When selecting Statement of Applicability on an existing risk assessment, the following error message appear.

![ericromang 2019-03-25 at 16 08 00](https://user-images.githubusercontent.com/545923/54931767-f3870680-4f19-11e9-9892-4c43ef653274.png)

The same error appear on a newly created risk analysis

The used version is 2.8.0

Regards

**Comment by cedricbonhomme** [comment] 2019-04-30 07:11
closing assuming this was a cache error like your last problem. This is generally this (anr/so resource is for sure not missing).

**Comment by eromang** [comment] 2019-05-02 05:58
Dear @cedricbonhomme,

The issue is not related to the cache and was not solved in version 2.8.0
I upgraded to version 2.8.1 and have the same issue.

When I select a risk assessment, the first page that is opened is directly the SoA, with the following error. 

![ericromang 2019-05-02 at 07 52 25](https://user-images.githubusercontent.com/545923/57058402-fd85ed00-6caf-11e9-86dd-d8de5edb1ae3.png)

Regards

**Comment by eurodude** [comment] 2019-11-06 12:57
Dear @eromang 

we are not able to reproduce this error. We do not have that error either on MONARC 2.9... Can you check the following, just to be sure:

1. are the permissions correctly set in the folders,
2. did you perform the updates with success including the databases
3. can you locate the files on your instance?

regards

**Comment by jfrocha** [comment] 2020-03-20 11:19
Error never reproduced.

**Closed by jfrocha** 2020-03-20 11:19 UTC
