### ISSUE TITLE
update-all.sh: Could not read from remote repository

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#365] opened 2021-07-14 09:15 UTC
**Describe the bug**
During updates or new installations there are currently problems accessing `ng-inline-edit.git'using update-all.sh. 

`[                  ] \ extractTree: sill extract uri-js@4.4.1 extracted to /var/www/html/test/node_modules/ng_client/node_mod`
`npm ERR! Error while executing:`
`npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/monarc-project/ng-inline-edit.git`
`npm ERR! `
`npm ERR! Could not create directory '/var/www/.ssh'.`
`npm ERR! Host key verification failed.`
`npm ERR! fatal: Could not read from remote repository.`
`npm ERR! `
`npm ERR! Please make sure you have the correct access rights`
`npm ERR! and the repository exists.`
`npm ERR! `
`npm ERR! exited with error code: 128`

**To Reproduce**
1. run update-all.sh script or run command directly from installation dir `git ls-remote -h -t ssh://git@github.com/monarc-project/ng-inline-edit.git`
2. See error

**Expected behavior**
updating the monarc installtion without error

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 20.04
| PHP version                             | 7.4
| MONARC version / git hash     | 2.10.4

**Comment by cedricbonhomme** [comment] 2021-07-15 05:58
Thank you for the report. The issue is confirmed and had already been reported. It will be fixed in the next release, we need to create a tag. A temporary solution [here](https://github.com/Oakenston/Monarc-Docker/commit/aa7e8a4c55df9e1d7a0099517ebd87fd456633d4) consists to replace ``git+ssh`` with ``https``.

**Comment by KonzeptAcht** [comment] 2021-07-15 06:04
Oh, I hadn't seen that. Sorry for the duplicate

**Comment by cedricbonhomme** [comment] 2021-07-15 06:11
No worry, we generally do not use this repository for issues reporting.

**Comment by cedricbonhomme** [comment] 2021-07-15 06:13
transferred [here](https://github.com/monarc-project/MonarcAppFO/issues/366) ;-)

**Closed** 2021-09-02 12:18 UTC
Labels: bug
