### ISSUE TITLE
Une erreur est survenue ... exported from MONARC v2.8.1 or lower are not supported

### ISSUE THREAD

**Issue by Solvap** [monarc-project/MonarcAppFO#458] opened 2022-10-03 09:12 UTC
Hello,

I've encountered the following bug on the MONARC v2.12.2 and as I didn't found any existing bug report addressing it, I've submitted this one myself.
**Describe the bug**
MONARC v2.12.2

This bug occurs when **importing** a risk analysis exported from MONARC v**2.12.2**.

**To Reproduce**
1. Export your risk analysis, even a newly created one, without password. The Export Options don't have any impact to this bug occurrence.
2. Click on Import the risk analysis
3. Select your .JSON file that has been exported previously.
4. Once you've clicked on the "Import" button, the following error message (or similar) appears:
5. `Une erreur est survenue sur api/client-anr/53/instances/import : Import of files exported from MONARC v2.8.1 or lower are not supported. Please contact us for more details. (500)`
6. Then, the import seems to hangs indefinitely and I have to click the Cancel button to get back access to MONARC interface.
7. Problem found: By checking the JSON file with a text editor, I've spotted that the version value is preceded by the letter "v". In other words, instead of having as version value "2.12.2", the value is "v2.12.2". So, by removing that letter, the bug doesn't occur and the import is successful.

**Expected behavior**
Instead of this error message, we should get see the imported risk analysis data with a confirmation that the import was successful.

**Screenshots**
![image](https://user-images.githubusercontent.com/24362212/193539647-acd252ad-655a-4ac4-918c-a8403554a89c.png)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 20.04
| OS version (client)                   | Win10
| PHP version                             | 
| MONARC version / git hash     | 2.12.2
| Browser                                    | Firefox, Chrome

**Additional context**
WORKAROUND: By checking the JSON file with a text editor, you should see that the version value is preceded by the letter "v". In other words, instead of having as version value "2.12.2", the value is "v2.12.2". So, by removing that letter, the bug shouldn't occur and the import should be successful.

Have a nice day.
Solvap

**Comment by ruslanbaidan** [comment] 2022-10-03 09:30
Hello,
Could you tell if the Monarc you use is installed on our clouds or on your side ?
I tried it on my.monarc.lu cloud and there is no `v` in the version.
If Monarc is installed on your side you need to check [the following file](https://github.com/monarc-project/MonarcAppFO/blob/master/package.json#L3).
Thank you.

**Comment by Solvap** [comment] 2022-10-03 09:37
Hello,

Sorry, I didn't mention that I use the OVA Image on VirtualBox.
Have a nice day,

Solvap

**Comment by ruslanbaidan** [comment] 2022-10-06 14:37
Hello,

Thank you for the information.
The issue is fixed within [a new release of Monarc](https://github.com/monarc-project/MonarcAppFO/releases/tag/v2.12.3).
You can download and use [a new VM](https://vm.monarc.lu/latest/).

**Closed by ruslanbaidan** 2022-10-06 14:37 UTC
Labels: bug, needs triage, potential-bug

**Comment by cponsard** [comment] 2023-01-26 06:52
Hello 

I & my students @UNamur had the problem with 2.12.2, the rename fix was very helpful
no problem with 2.12.4 used later (but we needed to migrated)
the error message was a bit confusing, maybe adapt it in case of error during import

some students reported a few problems with 2.12.but not at import time (will report separately
maybe also some "feature request or proposal")

thanks for the great work !
christophe

**Comment by ruslanbaidan** [comment] 2023-01-26 07:51
Hello,

Thank you for your feedback.
It would be better to migrate to the latest VM.

With regards
