### ISSUE TITLE
Error when trying to edit controls (within referentials view)

### ISSUE THREAD

**Issue by n1x0d** [monarc-project/MonarcAppFO#281] opened 2020-05-03 19:38 UTC
Hello folks!

First of all, thanks for giving us monarc. I found a bug that's preventing me from editing controls. 

Whenerver I try to edit a control, I get:
`An error occurred while fetching api/client-anr/3/measures/c8602299-2d41-4c54-8d41-86cfb03fcc2a: Argument 1 passed to Ramsey\Uuid\Uuid::isValid() must be of the type string, array given, called in /var/lib/monarc/fo/vendor/monarc/frontoffice/src/Controller/ApiAnrAbstractController.php on line 68 (500)`

I can create and delete controls just fine, but editing yields the error message stated above.

Language is set to English for the user the case.

Please advise.

Kind regards

**Comment by cedricbonhomme** [comment] 2020-05-03 22:10
Hi,
thank you very much for this report.
You were correct, this is bug. The issue is now fixed. It will be shipped soon in the next release.

**Comment by n1x0d** [comment] 2020-05-03 22:22
That was fix. Thank you.

**Closed** 2020-11-17 14:50 UTC
Labels: bug
