### ISSUE TITLE
Upgrade to ZendFramework3 known issues / improvements.

### ISSUE THREAD

**Issue by ruslanbaydan** [monarc-project/MonarcAppFO#193] opened 2019-11-05 09:05 UTC

**Comment by eurodude** [comment] 2019-11-06 12:52
Looks to be a duplicate of #15 or at least an extension...

**Comment by jerolomb** [comment] 2019-11-07 10:15
- [ ]  Snapshotting -> error 500 on the RPI on the anr_id 59

**Comment by cedricbonhomme** [comment] 2019-11-12 10:24
I managed to upgrade MONARC 2.2.0 (in an old Ubuntu Artful VM with PHP 7.1.11) to future 2.9.1 version, with this script:.

`$ curl -sSL https://raw.githubusercontent.com/monarc-project/website/master/content/assets/scripts/upgrade-to-2.9.1.sh | sudo -u www-data bash`

So it is working with PHP 7.1. Even if this is discouraged (https://www.php.net/supported-versions.php). We can warn users about this in the next blog post for the release.

**Comment by ruslanbaydan** [comment] 2019-11-27 15:20
Fixed

**Closed** 2019-11-27 15:20 UTC
